#!/usr/bin/env python3
import gzip
from pathlib import Path

# ==== Cấu hình đường dẫn tại đây ====
input_path = Path("index - Copy.html")        # File HTML đầu vào
output_path = Path("esp_idf_antispoof/main/camera_index.h")  # File header đầu ra
array_name = "index_ov2640_html_gz"       # Tên mảng trong file .h
# =====================================

# Đọc nội dung HTML
html_data = input_path.read_bytes()

# Nén bằng gzip (mức nén 9 là cao nhất)
gz_data = gzip.compress(html_data, compresslevel=9)

# Đảm bảo thư mục output tồn tại
output_path.parent.mkdir(parents=True, exist_ok=True)

# Ghi ra file .h
with output_path.open("w", encoding="utf-8") as f:
    f.write("// Auto-generated by html_to_header.py\n")
    f.write(f"// Source: {input_path}, Original size: {len(html_data)}, Gzipped size: {len(gz_data)}\n\n")
    f.write(f"#define {array_name}_len {len(gz_data)}\n")
    f.write(f"const uint8_t {array_name}[] = {{\n")
    for i, b in enumerate(gz_data):
        if i % 16 == 0:
            f.write("  ")
        f.write(f"0x{b:02X},")
        if (i + 1) % 16 == 0:
            f.write("\n")
        else:
            f.write(" ")
    if len(gz_data) % 16 != 0:
        f.write("\n")
    f.write("};\n")

print(f"Converted {input_path} -> {output_path}")
